FROM debian:bullseye-20230109-slim
RUN apt-get update
RUN apt-get install -y --no-install-recommends openssh-server
RUN update-rc.d ssh defaults
RUN update-rc.d ssh enable
COPY ./docker/configs/test_key.pub /root/.ssh/authorized_keys
