Vagrant.configure(2) do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provider :libvirt do |p|
    p.cpus = 2
    p.memory = 2048
  end

  servers = {0 => {"ip" => "192.168.56.2"}, 1 =>{"ip"=> "192.168.56.3"}, 2=>{"ip"=> "192.168.56.4"}, 3 => {"ip" => "192.168.56.5"}}
  servers.each do |key, value|
    config.vm.define "server#{key}" do |server|
      server.vm.network :private_network, ip: value["ip"]
      if key == 0
        server.vm.network "forwarded_port", guest: 9080, host: 9080
      end
    end
  end
end
