"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from enum import Enum
from typing import MutableMapping, TypeVar

class Strategy(Enum):
    REPLACE = ...
    ADDITIVE = ...
    TYPESAFE = ...
    TYPESAFE_REPLACE = ...
    TYPESAFE_ADDITIVE = ...

K = TypeVar("K")
V = TypeVar("V")

_handle_merge = ...

def merge(
    destination: MutableMapping[K, V], *sources: Mapping[K, V], strategy: Strategy = ...
) -> MutableMapping[K, V]:
    """
    A deep merge function for 🐍.

    :param destination: The destination mapping.
    :param sources: The source mappings.
    :param strategy: The merge strategy.
    :return:
    """
    ...
